/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./src/components/layout/admin/AdminLayout.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ExtensionSlot: typeof import('./src/components/ExtensionSlot.vue')['default']
    ForCreatorsSection: typeof import('./src/components/home/ForCreatorsSection.vue')['default']
    ForPlayersSection: typeof import('./src/components/home/ForPlayersSection.vue')['default']
    ForumContent: typeof import('./src/components/forum/ForumContent.vue')['default']
    ForumRightPanel: typeof import('./src/components/forum/ForumRightPanel.vue')['default']
    ForumSidebar: typeof import('./src/components/forum/ForumSidebar.vue')['default']
    HeroSection: typeof import('./src/components/home/HeroSection.vue')['default']
    HomeLayout: typeof import('./src/components/layout/HomeLayout.vue')['default']
    LoginModal: typeof import('./src/components/LoginModal.vue')['default']
    NewsSection: typeof import('./src/components/home/NewsSection.vue')['default']
    ProjectCard: typeof import('./src/components/home/ProjectCard.vue')['default']
    ProjectCarousel: typeof import('./src/components/home/ProjectCarousel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/layout/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/layout/TheHeader.vue')['default']
    UserFormModal: typeof import('./src/components/admin/UserFormModal.vue')['default']
    WkAlert: typeof import('./src/components/common/WkAlert.vue')['default']
    WkBadge: typeof import('./src/components/common/WkBadge.vue')['default']
    WkButton: typeof import('./src/components/common/WkButton.vue')['default']
    WkCard: typeof import('./src/components/common/WkCard.vue')['default']
    WkConfirmModal: typeof import('./src/components/common/WkConfirmModal.vue')['default']
    WkDialog: typeof import('./src/components/common/WkDialog.vue')['default']
    WkInput: typeof import('./src/components/common/WkInput.vue')['default']
    WkLegalModal: typeof import('./src/components/common/WkLegalModal.vue')['default']
    WkLoading: typeof import('./src/components/common/WkLoading.vue')['default']
    WkMarkdownEditor: typeof import('./src/components/common/WkMarkdownEditor.vue')['default']
    WkMarkdownRenderer: typeof import('./src/components/common/WkMarkdownRenderer.vue')['default']
    WkNotification: typeof import('./src/components/common/WkNotification.vue')['default']
  }
}
